# Rust formatting configuration (stable features only)
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
edition = "2021"